{
 "title": "Historischer Überblick der Energiegemeinschaft",
 "description": "Erzeugungs- und Verbrauchssummen der Energiegemeinschaft",
 "tags": [
  "energy",
  "community",
  "influxdb"
 ],
 "time": { "from": "2025-10-01T00:00:00Z", "to": "2025-11-12T00:00:00Z" },
 "panels": [
  {
   "title": "Erzeugung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Erzeugung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"total\")\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"Erzeugung\"})\n  |> keep(columns: [\"Erzeugung\"])"
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Verbrauch",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"total\")\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"Verbrauch\"})\n  |> keep(columns: [\"Verbrauch\"])"
    }
   ]
  },
  {
   "title": "An Gemeinschaft",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lieferung an Gemeinschaft",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"community_effective\")\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"Lieferung an Gemeinschaft\"})\n  |> keep(columns: [\"Lieferung an Gemeinschaft\"])"
    }
   ]
  },
  {
   "title": "Aus Gemeinschaft",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Bezug aus Gemeinschaft",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"community_effective\")\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"Bezug aus Gemeinschaft\"})\n  |> keep(columns: [\"Bezug aus Gemeinschaft\"])"
    }
   ]
  },
  {
   "title": "Netzbezug",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Netzbezug",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"residual\")\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"Netzbezug\"})\n  |> keep(columns: [\"Netzbezug\"])"
    }
   ]
  },
  {
   "title": "Netzeinspeisung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Restliche Einspeisung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"residual\")\n  |> group()\n  |> sum(column: \"_value\")\n  |> rename(columns: {_value: \"Restliche Einspeisung\"})\n  |> keep(columns: [\"Restliche Einspeisung\"])"
    }
   ]
  },
  {
   "title": "Erzeugung und Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Erzeugung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"total\")\n  |> group()\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Erzeugung\"})\n  |> keep(columns: [\"_time\", \"Erzeugung\"])"
    },
    {
     "alias": "Verbrauch",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"total\")\n  |> group()\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Verbrauch\"})\n  |> keep(columns: [\"_time\", \"Verbrauch\"])"
    }
   ]
  },
  {
   "title": "Gemeinschaftsenergie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "An Gemeinschaft geliefert",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"community_effective\")\n  |> group()\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"An Gemeinschaft geliefert\"})\n  |> keep(columns: [\"_time\", \"An Gemeinschaft geliefert\"])"
    },
    {
     "alias": "Aus Gemeinschaft verbraucht",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"community_effective\")\n  |> group()\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Aus Gemeinschaft verbraucht\"})\n  |> keep(columns: [\"_time\", \"Aus Gemeinschaft verbraucht\"])"
    }
   ]
  },
  {
   "title": "Restenergie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Restliche Einspeisung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"residual\")\n  |> group()\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Restliche Einspeisung\"})\n  |> keep(columns: [\"_time\", \"Restliche Einspeisung\"])"
    },
    {
     "alias": "Restlicher Bezug",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"residual\")\n  |> group()\n  |> aggregateWindow(every: 15m, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Restlicher Bezug\"})\n  |> keep(columns: [\"_time\", \"Restlicher Bezug\"])"
    }
   ]
  },
  {
   "title": "Tageswerte",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Tägliche Erzeugung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"total\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Tägliche Erzeugung\"})\n  |> keep(columns: [\"_time\", \"Tägliche Erzeugung\"])"
    },
    {
     "alias": "Täglicher Verbrauch",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"total\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Täglicher Verbrauch\"})\n  |> keep(columns: [\"_time\", \"Täglicher Verbrauch\"])"
    }
   ]
  },
  {
   "title": "Gemeinschaft täglich",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Tägliche Gemeinschaftslieferung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"community_effective\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Tägliche Gemeinschaftslieferung\"})\n  |> keep(columns: [\"_time\", \"Tägliche Gemeinschaftslieferung\"])"
    },
    {
     "alias": "Täglicher Gemeinschaftsverbrauch",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"community_effective\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Täglicher Gemeinschaftsverbrauch\"})\n  |> keep(columns: [\"_time\", \"Täglicher Gemeinschaftsverbrauch\"])"
    }
   ]
  },
  {
   "title": "Tägliche Restenergie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Tägliche Resteinspeisung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"residual\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Tägliche Resteinspeisung\"})\n  |> keep(columns: [\"_time\", \"Tägliche Resteinspeisung\"])"
    },
    {
     "alias": "Täglicher Restbezug",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"residual\")\n  |> group()\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"Täglicher Restbezug\"})\n  |> keep(columns: [\"_time\", \"Täglicher Restbezug\"])"
    }
   ]
  },
  {
   "title": "Prognose: Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Ist-Erzeugung",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"DELIVERY\" and r.category == \"total\")\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> rename(columns: {_value: \"Ist-Erzeugung\"})\n  |> keep(columns: [\"_time\", \"Ist-Erzeugung\"])"
    },
    {
     "alias": "Prognosen",
     "query": "latestRuns = from(bucket: v.defaultBucket)\n  |> range(start: time(v: \"1970-01-01T00:00:00Z\"))\n  |> filter(fn: (r) => r._measurement == \"forecast_run_metadata\" and r._field == \"generated_at\")\n  |> filter(fn: (r) => r.target == \"generation\")\n  |> group(columns: [\"target\", \"model\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"run_id\", \"target\", \"model\"])\nforecasts = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_forecasts\" and r._field == \"forecast_kwh\")\n  |> filter(fn: (r) => r.target == \"generation\")\njoin(tables: {forecasts: forecasts, latestRuns: latestRuns}, on: [\"run_id\", \"target\", \"model\"])\n  |> group(columns: [\"_time\", \"model\"])\n  |> mean(column: \"_value\")\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"model\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Prognose: Verbrauch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "kWh" } },
   "targets": [
    {
     "alias": "Ist-Verbrauch",
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_values\" and r._field == \"value_kwh\")\n  |> filter(fn: (r) => r.direction == \"CONSUMPTION\" and r.category == \"total\")\n  |> group(columns: [\"_time\"])\n  |> sum(column: \"_value\")\n  |> group()\n  |> rename(columns: {_value: \"Ist-Verbrauch\"})\n  |> keep(columns: [\"_time\", \"Ist-Verbrauch\"])"
    },
    {
     "alias": "Prognosen",
     "query": "latestRuns = from(bucket: v.defaultBucket)\n  |> range(start: time(v: \"1970-01-01T00:00:00Z\"))\n  |> filter(fn: (r) => r._measurement == \"forecast_run_metadata\" and r._field == \"generated_at\")\n  |> filter(fn: (r) => r.target == \"consumption\")\n  |> group(columns: [\"target\", \"model\"])\n  |> sort(columns: [\"_time\"], desc: true)\n  |> limit(n: 1)\n  |> keep(columns: [\"run_id\", \"target\", \"model\"])\nforecasts = from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"energy_forecasts\" and r._field == \"forecast_kwh\")\n  |> filter(fn: (r) => r.target == \"consumption\")\njoin(tables: {forecasts: forecasts, latestRuns: latestRuns}, on: [\"run_id\", \"target\", \"model\"])\n  |> group(columns: [\"_time\", \"model\"])\n  |> mean(column: \"_value\")\n  |> group()\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"model\"], valueColumn: \"_value\")"
    }
   ]
  }
 ]
}