apiVersion: 1

datasources:
  - name: InfluxDB Energy
    uid: influxdb-energy
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      defaultBucket: ${INFLUXDB_BUCKET}
      httpMode: POST
      organization: ${INFLUXDB_ORG}
      version: Flux
      product: InfluxDB OSS
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    editable: true
