name: day-ahead-forecast
services:
  influxdb:
    container_name: influxdb
    image: influxdb:3-core
    user: root
    ports:
      - 8181:8181
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    command:
      - influxdb3
      - serve
      - --admin-token-file=/var/lib/influxdb3/admin-token.json
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
      - --query-file-limit=20000
      - --disable-telemetry-upload
    volumes:
      - type: volume
        source: influxdb3-data
        target: /var/lib/influxdb3/data
      - type: volume
        source: influxdb3-plugins
        target: /var/lib/influxdb3/plugins
      - type: bind
        source: ./influxdb/admin-token.json
        target: /var/lib/influxdb3/admin-token.json
    secrets:
      - admin-token
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_FEATURE_TOGGLES_ENABLE: "newInfluxDSConfigPageDesign"
    volumes:
      - type: bind
        source: ./grafana/provisioning
        target: /etc/grafana/provisioning
        read_only: true
      - type: bind
        source: ./grafana/dashboards
        target: /var/lib/grafana/dashboards
        read_only: true
volumes:
  influxdb3-data:
  influxdb3-plugins:
secrets:
  admin-token:
    file: influxdb/admin-token.json
