quarkus.application.name=forecast-backend

energy.influx.url=${INFLUXDB_URL:http://localhost:8086}
energy.influx.org=${INFLUXDB_ORG:kirchdorf}
energy.influx.bucket=${INFLUXDB_BUCKET:energy}
energy.influx.measurement=energy_values
energy.influx.forecast-measurement=energy_forecasts
energy.influx.forecast-evaluation-measurement=forecast_evaluations
energy.influx.forecast-run-metadata-measurement=forecast_run_metadata
energy.influx.token=${INFLUXDB_TOKEN:}

energy.influx.write-batch-size=${ENERGY_INFLUX_WRITE_BATCH_SIZE:50000}
energy.influx.forecast-dataset-query-window=P1D
