energy.influx.url=http://localhost:8181
energy.influx.database=energy
energy.influx.measurement=energy_values
energy.influx.forecast-measurement=energy_forecasts
energy.influx.forecast-evaluation-measurement=forecast_evaluations
energy.influx.forecast-run-metadata-measurement=forecast_run_metadata
energy.influx.token=${INFLUXDB_TOKEN:}

energy.influx.write-batch-size=${ENERGY_INFLUX_WRITE_BATCH_SIZE:50000}
energy.influx.gzip-threshold-bytes=${ENERGY_INFLUX_GZIP_THRESHOLD_BYTES:1048576}
energy.influx.forecast-dataset-query-window=P1D
