energy.influx.url=http://localhost:8181
energy.influx.database=energy
energy.influx.measurement=energy_series
energy.influx.token=${INFLUXDB_TOKEN:}
energy.influx.write-batch-size=${ENERGY_INFLUX_WRITE_BATCH_SIZE:10000}
